# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{js2bookmarklet}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nathan L Smith"]
  s.date = %q{2009-11-12}
  s.default_executable = %q{js2bookmarklet}
  s.description = %q{Utility to create a bookmarklet from a JavaScript file}
  s.email = %q{nlloyds@gmail.com}
  s.executables = ["js2bookmarklet"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/js2bookmarklet",
     "lib/js2bookmarklet.rb",
     "test/fixtures/script.js",
     "test/test_js2bookmarklet.rb"
  ]
  s.homepage = %q{http://github.com/smith/js2bookmarklet/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{}
  s.test_files = [
    "test/test_js2bookmarklet.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<jsmin>, [">= 0"])
    else
      s.add_dependency(%q<jsmin>, [">= 0"])
    end
  else
    s.add_dependency(%q<jsmin>, [">= 0"])
  end
end

